from typing import Text
import pyautogui
import time

pyautogui.PAUSE = 0.01

pyautogui.press("winleft")
time.sleep(1)
pyautogui.write("bloco")
time.sleep(1)
pyautogui.press("enter")
time.sleep(1)

pyautogui.write("FREDAO")
pyautogui.press("enter")
pyautogui.write("FREDAO")
pyautogui.press("enter")
pyautogui.write(" FREDAO")
pyautogui.press("enter")
pyautogui.write("  FREDAO")
pyautogui.press("enter")
pyautogui.write("   FREDAO")
pyautogui.press("enter")
pyautogui.write("    FREDAO")
pyautogui.press("enter")
pyautogui.write("     FREDAO")
pyautogui.press("enter")
pyautogui.write("      FREDAO")
pyautogui.press("enter")
pyautogui.write("       FREDAO")
pyautogui.press("enter")
pyautogui.write("        FREDAO")
pyautogui.press("enter")
pyautogui.write("         FREDAO")
pyautogui.press("enter")
pyautogui.write("          FREDAO")
pyautogui.press("enter")
pyautogui.write("         FRE  DAO")
pyautogui.press("enter")
pyautogui.write("        FRE    DAO")
pyautogui.press("enter")
pyautogui.write("       FRE      DAO")
pyautogui.press("enter")
pyautogui.write("      FRE        DAO")
pyautogui.press("enter")
pyautogui.write("     FRE          DAO")
pyautogui.press("enter")
pyautogui.write("    FRE            DAO")
pyautogui.press("enter")
pyautogui.write("   FRE              DAO")
pyautogui.press("enter")
pyautogui.write("  FRE                DAO")
pyautogui.press("enter")
pyautogui.write(" FRE                  DAO")
pyautogui.press("enter")
pyautogui.write("FRE                    DAO")
pyautogui.press("enter")
pyautogui.write(" FRE                  DAO")
pyautogui.press("enter")
pyautogui.write("  FRE                DAO")
pyautogui.press("enter")
pyautogui.write("   FRE              DAO")
pyautogui.press("enter")
pyautogui.write("    FRE            DAO")
pyautogui.press("enter")
pyautogui.write("     FRE          DAO")
pyautogui.press("enter")
pyautogui.write("      FRE        DAO")
pyautogui.press("enter")
pyautogui.write("       FRE      DAO")
pyautogui.press("enter")
pyautogui.write("        FRE    DAO")
pyautogui.press("enter")
pyautogui.write("         FRE  DAO")
pyautogui.press("enter")
pyautogui.write("          FREDAO")
pyautogui.press("enter")
pyautogui.write("           FRDAO")
pyautogui.press("enter")
pyautogui.write("            FDAO")
pyautogui.press("enter")
pyautogui.write("             DAO")
pyautogui.press("enter")
pyautogui.write("            DAOE")
pyautogui.press("enter")
pyautogui.write("           DAORE")
pyautogui.press("enter")
pyautogui.write("          DAOFRE")
pyautogui.press("enter")
pyautogui.write("         DAO  FRE")
pyautogui.press("enter")
pyautogui.write("        DAO    FRE")
pyautogui.press("enter")
pyautogui.write("       DAO      FRE")
pyautogui.press("enter")
pyautogui.write("      DAO        FRE")
pyautogui.press("enter")
pyautogui.write("     DAO          FRE")
pyautogui.press("enter")
pyautogui.write("    DAO            FRE")
pyautogui.press("enter")
pyautogui.write("   DAO              FRE")
pyautogui.press("enter")
pyautogui.write("  DAO                FRE")
pyautogui.press("enter")
pyautogui.write(" DAO                  FRE")
pyautogui.press("enter")
pyautogui.write("DAO                    FRE")
pyautogui.press("enter")
pyautogui.write(" DAO                  FRE")
pyautogui.press("enter")
pyautogui.write("  DAO                FRE")
pyautogui.press("enter")
pyautogui.write("   DAO              FRE")
pyautogui.press("enter")
pyautogui.write("    DAO            FRE")
pyautogui.press("enter")
pyautogui.write("     DAO          FRE")
pyautogui.press("enter")
pyautogui.write("      DAO        FRE")
pyautogui.press("enter")
pyautogui.write("       DAO      FRE")
pyautogui.press("enter")
pyautogui.write("        DAO    FRE")
pyautogui.press("enter")
pyautogui.write("         DAO  FRE")
pyautogui.press("enter")
pyautogui.write("          DAOFRE")
pyautogui.press("enter")
pyautogui.write("           DAFRE")
pyautogui.press("enter")
pyautogui.write("            DFRE")
pyautogui.press("enter")
pyautogui.write("             FRE")
pyautogui.press("enter")
pyautogui.write("            FREO")
pyautogui.press("enter")
pyautogui.write("           FREAO")
pyautogui.press("enter")
pyautogui.write("          FREDAO")
pyautogui.press("enter")
pyautogui.write("         FRE  DAO")
pyautogui.press("enter")
pyautogui.write("        FRE    DAO")
pyautogui.press("enter")
pyautogui.write("       FRE      DAO")
pyautogui.press("enter")
pyautogui.write("      FRE        DAO")
pyautogui.press("enter")
pyautogui.write("     FRE          DAO")
pyautogui.press("enter")
pyautogui.write("    FRE            DAO")
pyautogui.press("enter")
pyautogui.write("   FRE              DAO")
pyautogui.press("enter")
pyautogui.write("  FRE                DAO")
pyautogui.press("enter")
pyautogui.write(" FRE                  DAO")
pyautogui.press("enter")
pyautogui.write("FRE                    DAO")
pyautogui.press("enter")
pyautogui.write(" FRE                  DAO")
pyautogui.press("enter")
pyautogui.write("  FRE                DAO")
pyautogui.press("enter")
pyautogui.write("   FRE              DAO")
pyautogui.press("enter")
pyautogui.write("    FRE            DAO")
pyautogui.press("enter")
pyautogui.write("     FRE          DAO")
pyautogui.press("enter")
pyautogui.write("      FRE        DAO")
pyautogui.press("enter")
pyautogui.write("       FRE      DAO")
pyautogui.press("enter")
pyautogui.write("        FRE    DAO")
pyautogui.press("enter")
pyautogui.write("         FRE  DAO")
pyautogui.press("enter")
pyautogui.write("          FREDAO")
pyautogui.press("enter")
pyautogui.write("           FRDAO")
pyautogui.press("enter")
pyautogui.write("            FDAO")
pyautogui.press("enter")
pyautogui.write("             DAO")
pyautogui.press("enter")
pyautogui.write("            DAOE")
pyautogui.press("enter")
pyautogui.write("           DAORE")
pyautogui.press("enter")
pyautogui.write("          DAOFRE")
pyautogui.press("enter")
pyautogui.write("         DAO  FRE")
pyautogui.press("enter")
pyautogui.write("        DAO    FRE")
pyautogui.press("enter")
pyautogui.write("       DAO      FRE")
pyautogui.press("enter")
pyautogui.write("      DAO        FRE")
pyautogui.press("enter")
pyautogui.write("     DAO          FRE")
pyautogui.press("enter")
pyautogui.write("    DAO            FRE")
pyautogui.press("enter")
pyautogui.write("   DAO              FRE")
pyautogui.press("enter")
pyautogui.write("  DAO                FRE")
pyautogui.press("enter")
pyautogui.write(" DAO                  FRE")
pyautogui.press("enter")
pyautogui.write("DAO                    FRE")
pyautogui.press("enter")
pyautogui.write(" DAO                  FRE")
pyautogui.press("enter")
pyautogui.write("  DAO                FRE")
pyautogui.press("enter")
pyautogui.write("   DAO              FRE")
pyautogui.press("enter")
pyautogui.write("    DAO            FRE")
pyautogui.press("enter")
pyautogui.write("     DAO          FRE")
pyautogui.press("enter")
pyautogui.write("      DAO        FRE")
pyautogui.press("enter")
pyautogui.write("       DAO      FRE")
pyautogui.press("enter")
pyautogui.write("        DAO    FRE")
pyautogui.press("enter")
pyautogui.write("         DAO  FRE")
pyautogui.press("enter")
pyautogui.write("          DAOFRE")
pyautogui.press("enter")
pyautogui.write("           DAFRE")
pyautogui.press("enter")
pyautogui.write("            DFRE")
pyautogui.press("enter")
pyautogui.write("             FRE")
pyautogui.press("enter")
pyautogui.write("            FREO")
pyautogui.press("enter")
pyautogui.write("           FREAO")
pyautogui.press("enter")
pyautogui.write("          FREDAO")